version: "3.8"
services:

   mysql:
      image: mysql:8
      container_name: mysql
      ports:
         - 3306:3306
         - 33060:33060
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=bootdb
      networks:
         - fav-movie-network
         
   favmovie:
      build:
         dockerfile: ./Dockerfile
         context: ./
      image: leonardojunior/fav-movie
      container_name: fav-movie
      ports:
         - 8080:8080
      environment:
         - PORT=8080
         - MYSQL_CONTAINER=mysql
         - SPRING_PROFILES_ACTIVE=prod 
      networks:
         - fav-movie-network
      depends_on:
         - mysql

networks:
   fav-movie-network:
      driver: bridge