INSERT INTO CATEGORY(name) VALUES('horror');
INSERT INTO CATEGORY(name) VALUES('action');
INSERT INTO CATEGORY(name) VALUES('comedy');

INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, box_office, category_id)
VALUES('tt0468569', 'The Dark Knight', 'PG-13', '18 Jul 2008', '152 min', 'Action, Crime, Drama', 'Christopher Nolan', 'Jonathan Nolan, Christopher Nolan, David S. Goyer', 'Christian Bale, Heath Ledger, Aaron Eckhart', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'English', 'United States', 'Won 2 Oscars. 159 wins & 163 nominations total', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', '9.0', '2,574,403', 'movie', '$534,987,076', 2);
INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, box_office, category_id)
VALUES('tt1745960', 'Top Gun: Maverick', 'PG-13', '27 May 2022', '130 min', 'Action, Drama', 'Joseph Kosinski', 'Jim Cash, Jack Epps Jr, Peter Craig', 'Tom Cruise, Jennifer Connelly, Miles Teller', 'After more than thirty years of service as one of the Navys top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground', 'English', 'United States', 'n/a', 'https://m.media-amazon.com/images/M/MV5BOWQwOTA1ZDQtNzk3Yi00ZmVmLWFiZGYtNjdjNThiYjJhNzRjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg', '8.6', '195,758', 'movie', '$520,836,963', 2);
INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, box_office, category_id)
VALUES('tt8041270', 'Jurassic World Dominion', 'PG-13', '10 Jun 2022', '147 min', 'Action, Adventure', 'Colin Trevorrow', 'Emily Carmichael, Colin Trevorrow, Derek Connolly', 'Chris Pratt, Bryce Dallas Howard, Laura Dern', 'Four years after the destruction of Isla Nublar, dinosaurs now live and hunt alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain t...', 'English', 'United States', 'n/a', 'https://m.media-amazon.com/images/M/MV5BOTBjMjA4NmYtN2RjMi00YWZlLTliYTktOTIwMmNkYjYxYmE1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg', '6.0', '61,477', 'movie', '$306,487,740', 2);
INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, total_seasons, category_id)
VALUES('tt0944947', 'Game of Thrones', 'TV-MA', '17 Apr 2011', '58 min', 'Action, Adventure, Drama', ' Alex Graves, David Nutter, Mark Mylod', 'David Benioff, D.B. Weiss', 'Emilia Clarke, Peter Dinklage, Kit Harington', 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.', 'English', 'United States, United Kingdom', 'Won 59 Primetime Emmys. 387 wins & 632 nominations total', 'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg', '9.2', '2,009,949', 'series', '8', 2);
INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, box_office, category_id)
VALUES('tt9419884', 'Doctor Strange in the Multiverse of Madness', 'PG-13', '06 May 2022', '126 min', 'Action, Adventure, Fantasy', 'Sam Raimi', 'Michael Waldron, Stan Lee, Steve Ditko', 'Benedict Cumberbatch, Elizabeth Olsen, Chiwetel Ejiofor', 'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the mul...', 'English', 'United States', 'n/a', 'https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_SX300.jpg', '7.0', '313,010', 'movie', '$411,206,611', 2);
INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, category_id)
VALUES('tt12327578', 'Star Trek: Strange New Worlds', 'TV-PG', '05 May 2022', 'n/a', 'Action, Adventure, Sci-Fi', 'Akiva Goldsman...', 'Akiva Goldsman, Alex Kurtzman, Jenny Lumet', 'Melissa Navia, Anson Mount, Ethan Peck', 'A prequel to Star Trek: The Original Series, the show will follow the crew of the USS Enterprise under Captain Christopher Pike.', 'English', 'United States', 'n/a', 'https://m.media-amazon.com/images/M/MV5BYWNlYmZkZjQtNjU5OS00YTNkLWJmOTEtYmZiMmUwZGI3NTM3XkEyXkFqcGdeQXVyMTM2NTIwMDIw._V1_SX300.jpg', '8.2', '17,758', 'series', 2);
INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, box_office, category_id)
VALUES('tt0082418', 'Friday the 13th Part 2', 'R', '01 May 1981', '87 min', 'Horror, Mystery, Thriller', 'Steve Miner', 'Ron Kurz, Victor Miller, Sean S. Cunningham', 'Betsy Palmer, Amy Steel, John Furey', 'Five years after the events of the first film, a summer camp next to the infamous Camp Crystal Lake is preparing to open, but the legend of Jason is weighing heavy on the proceedings.', 'English', 'United States', '3 nominations', 'https://m.media-amazon.com/images/M/MV5BYTZmMjk1ZjAtZjg0Yy00MWIyLWI5NmYtMThlYmU3NTc2NzdkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', '6.0', '67,296', 'movie', '$21,722,776', 1);
INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, category_id)
VALUES('tt4574334', 'Stranger Things', 'TV-14', '15 Jul 2016', '51 min', 'Drama, Fantasy, Horror', 'n/a', 'Matt Duffer, Ross Duffer', 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder', 'hen a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.', 'English, Russian', 'United States', 'Won 7 Primetime Emmys. 77 wins & 241 nominations total', 'https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', '8.7', '1,092,107', 'series', 1);
INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, box_office, category_id)
VALUES('tt7144666', 'The Black Phone', 'R', '24 Jun 2022', '103 min', 'Horror', 'Scott Derrickson', 'Joe Hill, Scott Derrickson, C. Robert Cargill', 'Mason Thames, Madeleine McGraw, Ethan Hawke', 'After being abducted by a child killer and locked in a soundproof basement, a 13-year-old boy starts receiving calls on a disconnected phone from the killers previous victims.', 'English', 'United States', '1 nomination', 'https://m.media-amazon.com/images/M/MV5BOWVmNTBiYTUtZWQ3Yi00ZDlhLTgyYjUtNzBhZjM3YjRiNGRkXkEyXkFqcGdeQXVyNzYyOTM1ODI@._V1_SX300.jpg', '7.3', '17,603', 'movie', '$39,064,325', 1);
INSERT INTO MOVIE(imdbID, title, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, imdb_rating, imdb_votes, type, box_office, category_id)
VALUES('tt18968540', 'Incantation', 'TV-MA', '08 Jul 2022', '110 min', 'Horror', 'Kevin Ko', 'Che-Wei Chang, Kevin Ko', 'Hsuan-yen Tsai, Mohamed Elgendy, Ying-Hsuan Kao', 'WARNING: This is a cursed video, it might contain certain risks to watch ; For those who dares to follow, please solve the puzzle of my daughters curse with me.', 'Chinese', 'Taiwan', 'n/a', 'https://m.media-amazon.com/images/M/MV5BYjUxZGI1ODQtMDljMS00ZTUwLWI0NTMtYjc2YmUyZTM3YTdhXkEyXkFqcGdeQXVyNTM2NTY4NzU@._V1_SX300.jpg', '6.3', '2,872', 'movie', 'n/a', 1);
